code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension percygrunwald.vscode-intellij-recent-files
code --install-extension techer.open-in-browser
code --install-extension vscodevim.vim
code --install-extension mikestead.dotenv
code --install-extension eamodio.gitlens
